version: '3.5'
services:
  nginx:
    container_name: c-nginx
    image: nginx:alpine
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /vaw/www:/var/www
